#!/bin/bash

# 1st arg. : the number of the iteration of python command execution of the file

FILENAME='main'

# for record the polDict .pt file names in ONE file
date2=$(TZ=JST-9 date +'%Y-%m-%d-%T')
if [[ -z "${DIRECTORY_RESULTFILES}" ]]; then
  # DIRECTORY_RESULTFILES is UNDEFINED
  export DIRECTORY_RESULTFILES=$date2 
  echo -n "set "
  printenv | grep DIRECTORY_RESULTFILES
else
  # DIRECTORY_RESULTFILES has ALREADY been set
  echo "CUDA_VISIBLE_DEVICES HAS BEEN set, <-- something wrong"
  exit
fi

iter=1
while [ $iter -le $1 ];do
  python main.py
  iter=$(($iter + 1))
done

unset DIRECTORY_RESULTFILES 
echo "DIRECTORY_RESULTFILES unset"